const userProfile = {
  name: 'DIPALI SHASHANK JARI KOTE',
  firstName: 'DIPALI',
  savingsBalance: ',2,000.00',
  custId: '******54',
  username: '41701989',
  dob: '12/**/****',
  pan: 'D*******2L',
  aadhar: '********4309',
  ckyc: '**********8476',
  mobile: '77****1055',
  email: 'ke*************@gmail.com',
  permanentAddress: {
    line1: '107 Near 38 Chari Karande Wasti',
    line2: 'Golande Niwas Ukkadgaon',
    city: 'AHMEDNAGAR',
    state: 'MAHARASHTRA',
    pincode: '413702',
  },
  communicationAddress: {
    line1: 'A-406, SAPPHIRE SAI NISARG',
    line2: 'UDHYOG NAGAR',
    line3: 'CHINCHWAD',
    city: 'PUNE',
    state: 'MAHARASHTRA',
    pincode: '411033',
  },
  accountNumber: '2601235010795688',
  accountType: 'AU Salary Account-Value',
  customerType: 'Individual - Full KYC',
  branch: 'Wakad Pune',
  ifsc: 'AUBL0002350',
  nominee: 'Not Registered',
  annualIncome: '2.5 Lakh - 5 Lakh',
  profileComplete: 83,
}

export default userProfile
