const userProfile = {
  name: 'PRANAY MANOHAR SURYAWANSHI',
  firstName: 'DIPALI',
  savingsBalance: ',2,000.00',
  custId: '******54',
  username: '42866828',
  dob: '12/**/****',
  pan: 'D*******2L',
  aadhar: '********4309',
  ckyc: '**********8476',
  mobile: '77****1055',
  email: 'ke*************@gmail.com',
  permanentAddress: {
    line1: '107 Near 38 Chari Karande Wasti',
    line2: 'Golande Niwas Ukkadgaon',
    city: 'AHMEDNAGAR',
    state: 'MAHARASHTRA',
    pincode: '413702',
  },
  communicationAddress: {
    line1: 'OFFICE NO 101, GANESHAM A BUILDING',
    line2: 'BRTS ROAD',
    line3: 'PIMPLE SAUDAGAR',
    city: 'PUNE',
    state: 'MAHARASHTRA',
    pincode: '411027',
  },
  accountNumber: '2601235316331578',
  accountType: 'AU Salary Account-Value',
  customerType: 'Individual - Full KYC',
  branch: 'Aundh Pune',
  ifsc: 'AUBL0002353',
  nominee: 'Not Registered',
  annualIncome: '2.5 Lakh - 5 Lakh',
  profileComplete: 83,
}

export default userProfile
